sudo: required
dist: trusty

language: node_js
node_js: "stable"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  firefox: "latest"

cache:
  directories:
    - "node_modules"
    - "~/.npm"

before_install:
  # Use X Virtual Frame Buffer
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1027x768x16"
  - sleep 3 # give xvfb some time to start
  - "export DISPLAY=:99.0"

  # Install NPM dependencies
  - npm install

  # Cache Chimp's Selenium & ChromeDriver downloads
  - mkdir ./tmp && ./node_modules/.bin/chimp --path=./tmp && rm -rf ./tmp # there are no tests here

  # Cache Karma's dependencies
  - ./node_modules/.bin/karma start ./config/karma.config.js || true

script:
  - npm test
