sudo: false

language: node_js

node_js:
  - 6.3.0

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  firefox: "latest"

cache:
  directories:
    - "$HOME/node_modules"
    - "$HOME/.npm"

before_install:
  # Use X Virtual Frame Buffer
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1027x768x16"
  - sleep 3 # give xvfb some time to start
  - "export DISPLAY=:99.0"

  # Install NPM dependencies
  - npm install

  # Cache Selenium & ChromeDriver
  - mkdir ./temporaryDirectory
  - ./node_modules/.bin/chimp --path=./temporaryDirectory # there are no tests here
  - rm -rf ./temporaryDirectory

  # Cache Karma dependencies
  - ./node_modules/.bin/karma start ./config/karma.config.js

script:
  - npm test
