sudo: required
dist: trusty

env:
  global:
    - DEPLOY_SITE=qualityfaster
    - BROWSER=chrome

language: node_js
node_js: "stable"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  firefox: "latest"

cache:
  directories:
    - "node_modules"
    - "~/.npm"
    - "~/.meteor"
    - "src/node_modules"
    - "src/.meteor/local/build"
    - "src/.meteor/local/bundler-cache"
    - "src/.meteor/local/db"
    - "src/.meteor/local/isopacks"
    - "src/.meteor/local/plugin-cache"

before_cache:
  - rm -rf ~/build/xolvio/qualityfaster/.meteor/local/log
  - rm -rf ~/build/xolvio/qualityfaster/.meteor/local/run

before_install:
  # Use X Virtual Frame Buffer
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1027x768x16"
  - sleep 3 # give xvfb some time to start
  - "export DISPLAY=:99.0"

install:
  # Install NPM dependencies
  - npm install

  # Cache Chimp's Selenium & ChromeDriver downloads
  - mkdir ./tmp && ./node_modules/.bin/chimp --path=./tmp && rm -rf ./tmp # there are no tests here

  # Cache Karma's dependencies
  - ./node_modules/.bin/karma start ./config/karma.config.js || true

  # Install & Cache Meteor
  - scripts/install-meteor.sh

script:
  - npm test

# For the deployment code below to work, you need to first carry out the following steps on your local machine:
# 1.  Create a Meteor developer account and sign-up for Galaxy
# 2a. Login with Meteor and save the session to file
#     METEOR_SESSION_FILE=meteor-session-file.json meteor login
# 2b. Use Node.js to encode and output the file as a Base64 string
#     FILE_CONTENT=`cat meteor-session-file.json` node -e "console.log(new Buffer(process.env.FILE_CONTENT).toString('base64'))"
# 3.  Copy & paste the output in an environment variable called METEOR_SESSION_FILE_CONTENT in the project settings on TravisCI

deploy:
  # We deploy to production any time the previous test step passed AND...
  provider: script
  # We use the script to deploy
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    # ...when the commit is made to this branch
    branch: dev
